config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # ルートパスへアクセスがあったらmessages_controllerのindexアクションが呼び出される
  root to: "rooms#index"
  resources :users, only: [:edit, :update]
  # どのルームで投稿されたメッセージなのかをパスから判断できるようにしたいので、ルーティングのネストを利用
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  # 以下のメソッドによって各レコードとファイルを1対1の関係で紐づける
  # :ファイル名の記述により、モデル.ファイル名で添付されたファイルにアクセスできる
  # また、このファイル名は、そのモデルが紐付いたフォームから送られるパラメーターのキーにもなる
  has_one_attached :image

  # unlessオプションにメソッド名を指定することで、「メソッドの返り血がfalseならばバリデーションによる検証を行う」という条件を作っている
  validates :content, presence: true, unless: :was_attached?

  # 以下は、画像があればtrue、なければfalseを返すメソッド
  # レコードにファイルが添付されているかどうかでtrue,falseを返すattached?メソッドを使用
  def was_attached?
    self.image.attached?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  # dependentオプションに:destroyを指定すると、親モデルが削除された時、それに紐付いている子モデルも一緒に削除される
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # 処理が呼ばれた段階で、ユーザーがログインしていなければ、そのユーザーをログイン画面に遷移させるdeviseのメソッド
  before_action :authenticate_user!
  # メソッド名は慣習。実際は名前は何でもOK
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private

  def configure_permitted_parameters
    # deviseにおけるparamsのようなメソッド。deviseのUserモデルにパラメーターを許可
    # :sign_upはdeviseの処理名。keysで、配列で指定された名前と同じキーを持つパラメーターの取得を許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    # ルーティングをネストしているため、/rooms/:room_id/messagesといったパスになっている
    # パスにroom_idが含まれているため、paramsというハッシュオブジェクトの中に、room_idという値が存在している
    @room = Room.find(params[:room_id])
    @message = Message.new
    # チャットルームに紐付いている全てのメッセージを@messageと定義。メッセージに紐付くユーザー情報の取得に、
    # メッセージの数と同じ回数のアクセスが必要なため、includes(:user)とすることでN+1問題を解消
    @messages = @room.messages.includes(:room)
  end

  def create
    @room = Room.find(params[:room_id])
    # @room.messages.newでチャットルームに紐づいたメッセージのインスタンス(messagesテーブルだからmessages)を生成し、message_paramsを引数にして、privateメソッドを呼び出す
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      # 投稿に失敗したときにindex.html.erbを参照するが、renderではindexアクションを経由しないため、@messagesが定義されていないとエラーになる。そのため、indexアクションと同様に@messageを定義する必要あり
      @messages = @room.messages.includes(:room)
      render :index
    end
  end

  private
  def message_params
    # パラメーターの中に、ログインしているuserのidと紐づいているメッセージの内容(content,image)を受け取れるように許可
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def index
  end

  def destroy
    # destroyアクションは削除するだけであるため、ビューの表示は必要ない。そのため、インスタンス変数ではなくローカル変数でよい
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    # permitの「user_ids: []」という記述は、配列に対して保存を許可したい場合、キーに対し[]を値として記述する
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    # current_userメソッドにはユーザー情報が格納されている
    if current_user.update(user_params)
      # redirect_toメソッドは新たなリクエストを送信されたときと同じで、再度ルーティング、コントローラーを経由してビューを表示する
      redirect_to root_path
    else
      # renderメソッドは新たにリクエストされることなくそのままビューを表示する
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Yahoo!が開発した「YUI3」というリセットCSSを公式GitHubから読み込む %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%# 削除するチャットルームを区別するために、定義している@roomを引数にしている %>
      <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
    </div>
  </div>
</div>

<div class="messages">
  <%# renderメソッドのcollectionオプションは、指定したインスタンス変数の中にある要素の数だけ、部分テンプレートが繰り返し表示される %>
  <%# collectionオプションを使えば、eachメソッドを使用しないでrenderを繰り返し表示できる %>
  <%= render partial: 'message', collection: @messages %>
</div>
<%# form_withの引数に@room, @messageを渡しているのは、messagesのルーティングがroomsにネストされているため %>
<%# @roomには「指定のチャットルームのレコード情報」、@messageには「Messageモデルの空のインスタンス(Message.new)」を予めセットする必要がある %>
<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%# バリデーションで空のメッセージを保存できなくなったが、エラー発生時、問題のあったinput要素を囲うように、エラ〜メッセージ表示用のdiv要素がrailsによって生成され、CSSの指定に齟齬が発生する。これに関してCSSを編集する必要がある %>
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <%# label要素はフォームの中でフォームの項目名とフォームの入力要素(画像選択フォーム、プルダウン、チェックボックスなど)を関連づけるための要素 %>
    <%# label要素の役割の一つとして、label要素がクリックされたときに、子要素もクリックされたことにしてくれる。この仕組みで見えないはずのファイル選択ボタンをクリックしたかのように動作させられる %>
    <label class='form-image'>
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.name%>
    </div>
    <div class="message-date">
      <%# lメソッドは日付や時刻を表示するRailsのメソッド。configでの設定が必要 %>
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.content %>
    </div>
    <%# image_tagメソッドでは複雑なRailsのディレクトリパスを指定しなくてもモデルから画像ファイルを呼び出して引数に指定するだけで画像を表示するimg要素を生成する %>
    <%# 「image_tag モデル.画像ファイル」または「image_tag (app/assets/)画像のファイルのパス %>
    <%# レコードにファイルが添付されているかどうかでtrue,falseを返すattached?メソッドを使用。画像が存在する場合のみimage_tagが読み込まれる %>
    <%# variantメソッドはActive Storageを導入している場合に使用可能。モデル名.ファイル名.variant(resize: '幅x高さ')で指定されたサイズ以下に変換する %>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%# link_toのパスを、ログインしているユーザーの編集をするため、以下のパスの記述をしている %>
    <%= link_to current_user.name, edit_user_path(current_user) %>
  </div>
  <div class="create-room">
    <%= link_to "チャットを作成する", new_room_path %>
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room|%>
    <div class="room">
      <div class="room-name">
        <%# path(room)とすることで、メッセージと紐づいているチャットルームのidを持たせられる %>
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
      <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%# form_withのブロック変数からフォーム部品を追加しているため、「room」キーの中に「name」キーが入る仕組み %>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <%# select要素はプルダウンのようなセレクトボックスを作成するための要素 %>
        <%# select要素のname属性に任意の値を指定することでparamsを通して、その値をコントローラーへ渡すことができる %>
        <%# 以下のname属性の記述によって送られるパラメーターは{"room" => {"user_ids" => ["選択したuser.id"]}} 2重ハッシュ構造になっている %>
        <select name="room[user_ids][]">
          <%# select要素の中に記述することでプルダウンの選択肢になる要素 %>
          <option value="">チャットするユーザーを選択してください</option>
          <%# モデル名.where("条件")と記述すると、条件に一致したレコードを配列として取得できる %>
          <%# モデル名.where.not("条件")は、条件に一致したレコード以外の値を配列として取得できる %>
          <% User.where.not(id: current_user.id).each do |user| %>
            <%# value属性で指定されたuser.idがname属性のroom[user_ids][user.id]として格納される %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <%# 以下の記述で、現在ログイン中のuserが持つidをparams"room[user_ids][]に追加で格納している %>
        <%# type属性にhiddenを指定することで、画面上には表示されないinput要素を作成できる %>
        <%# この記述の結果、コントローラーに送られるparamsは{"room" => {"user_ids" => ["選択したuser.id", "現在ログイン中のuser.id"]となる %>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>